version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-patch:
        update-types:
          - patch
      all-development:
        dependency-type: "development"
      rollup:
        patterns:
          - "@rollup/**"

  - package-ecosystem: "npm"
    directory: "/demos"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
