name: Build and test on every commit

on:
  push:
    branches:
      - "**"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npx pnpm@latest-10 i --frozen-lockfile
      - name: Cache node_modules
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

  typescript:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: TypeScript check
        run: npx pnpm@latest-10 tsc

  lint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Lint
        run: npx pnpm@latest-10 lint

  prettier:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Prettier check
        run: npx pnpm@latest-10 prettier

  build:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build
        run: npx pnpm@latest-10 build
